heroku container:login

heroku container:push -a calpoly-csai-nimbus web --arg DATABASE_HOSTNAME,DATABASE_PASSWORD,DATABASE_USERNAME,DATABASE_NAME,PYDRIVE_CLIENT_ID,PYDRIVE_CLIENT_SECRET,GOOGLE_DRIVE_CREDENTIALS,GOOGLE_DRIVE_FOLDER_ID,GOOGLE_CLOUD_NLP_CREDENTIALS,GOOGLE_CLOUD_NLP_MODEL_NAME

heroku container:release -a calpoly-csai-nimbus web
