name: Run Tests

on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches:
      - master
      - dev
  pull_request_review_comment:
    types: [created]

jobs:
  run_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip install hypothesis

    - name: Test with hypothesis
      run: ./run_tests.sh
