name: Python Pyre Type Annotation Check

on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches:
      - master
      - dev

jobs:
  type_check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the Type Checker
      run: |
        echo "todo..."
        ./type_check.sh
    - name: Run Type Annotation Coverage
      run: |
        echo "todo..."
        echo "todo..."